import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Product } from '../models/product'
import { db } from '../utils/database'

export default function Home({ products }) {
  console.log(products)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        xxxx
        <div style={{ width: '100%', heigth: '100vw', backgroundColor: 'red' }}>
          x
          {
            products.map((item, index) => (
              <h1>{item.name}</h1>
            ))
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  await db.connect();
  const products = await Product.find().lean();

  return {
    props: {
      products: products.map(db.convertDocToObj),
    },
  };
}

